'use client';

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { motion } from "framer-motion";
import { ArrowLeft, Download, Share2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import VisualRoadmap from "@/components/VisualRoadmap";

export default function RoadmapPage() {
    const router = useRouter();
    const [roadmapData, setRoadmapData] = useState(null);

    useEffect(() => {
        const savedData = localStorage.getItem('project-roadmap');
        if (savedData) {
            try {
                setRoadmapData(JSON.parse(savedData));
            } catch (e) {
                console.error("Failed to parse roadmap data", e);
                router.push('/discuss');
            }
        } else {
            router.push('/discuss');
        }
    }, [router]);

    const exportToMarkdown = () => {
        if (!roadmapData) return;

        let md = `# Strategy Roadmap: ${roadmapData.problem_statement || 'Project Plan'}\n\n`;
        md += `## Target Users\n${roadmapData.target_users}\n\n`;
        md += `## Key Assumptions\n${roadmapData.key_assumptions?.map(a => `- ${a}`).join('\n')}\n\n`;
        md += `## MVP Features\n${roadmapData.mvp_features?.map(f => `- ${f}`).join('\n')}\n\n`;
        md += `## Execution Phases\n\n`;
        roadmapData.roadmap_phases?.forEach(phase => {
            md += `### ${phase.phase}\n${phase.tasks?.map(t => `- ${t}`).join('\n')}\n\n`;
        });
        md += `## Top Risks\n${roadmapData.risks?.map(r => `- ${r}`).join('\n')}\n\n`;
        md += `## Open Questions\n${roadmapData.open_questions?.map(q => `- ${q}`).join('\n')}\n`;

        const blob = new Blob([md], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `roadmap-${Date.now()}.md`;
        a.click();
    };

    if (!roadmapData) return null;

    return (
        <div className="min-h-screen bg-background">
            {/* Header */}
            <header className="fixed top-0 left-0 right-0 z-50 bg-background/80 backdrop-blur-md border-b border-border">
                <div className="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between">
                    <Button
                        variant="ghost"
                        onClick={() => router.push("/discuss")}
                        className="text-muted-foreground"
                    >
                        <ArrowLeft className="w-4 h-4 mr-2" />
                        Back to Chat
                    </Button>

                    <div className="flex items-center gap-2">
                        <Button variant="outline" size="sm" className="hidden sm:flex">
                            <Share2 className="w-4 h-4 mr-2" />
                            Share
                        </Button>
                        <Button
                            size="sm"
                            onClick={exportToMarkdown}
                            className="gradient-bg text-primary-foreground shadow-glow"
                        >
                            <Download className="w-4 h-4 mr-2" />
                            Export Markdown
                        </Button>
                    </div>
                </div>
            </header>

            <main className="pt-24 pb-20">
                <VisualRoadmap data={roadmapData} />
            </main>

            {/* Footer / Disclaimer */}
            <footer className="py-12 border-t border-border bg-card/30 text-center">
                <p className="text-sm text-muted-foreground max-w-md mx-auto px-4">
                    This roadmap was generated by your AI Co-founder based on your vision and collaborative discussion.
                </p>
            </footer>
        </div>
    );
}
