'use client';

import { motion, AnimatePresence } from "framer-motion";
import { Download, FileText, Printer, X, Copy } from "lucide-react";
import { Button } from "@/components/ui/button";
import ReactMarkdown from 'react-markdown';
import { useAlert } from "@/context/AlertContext";

export default function ProjectSummary({ summary, isOpen, onClose }) {
    const { showSuccess } = useAlert();

    const handleCopy = () => {
        navigator.clipboard.writeText(summary);
        showSuccess("Copied", "Report content added to clipboard.");
    };

    const handlePrint = () => {
        window.print();
    };

    const handleDownload = () => {
        const blob = new Blob([summary], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `project-summary-${Date.now()}.md`;
        a.click();
        showSuccess("Summary Downloaded", "Strategic brief saved to your device.");
    };

    return (
        <AnimatePresence>
            {isOpen && (
                <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        onClick={onClose}
                        className="absolute inset-0 bg-black/60 backdrop-blur-md"
                    />

                    <motion.div
                        initial={{ opacity: 0, scale: 0.95, y: 20 }}
                        animate={{ opacity: 1, scale: 1, y: 0 }}
                        exit={{ opacity: 0, scale: 0.95, y: 20 }}
                        className="relative w-full sm:max-w-4xl h-[95vh] sm:h-auto max-h-[95vh] bg-card border border-border rounded-2xl sm:rounded-3xl shadow-2xl overflow-hidden flex flex-col print:shadow-none print:border-none print:max-h-none print:relative print:w-full"
                    >
                        {/* Header - Hidden on print */}
                        <div className="p-4 sm:p-6 border-b border-border flex items-center justify-between bg-card shrink-0 print:hidden">
                            <div className="flex items-center gap-2">
                                <FileText className="w-5 h-5 text-primary" />
                                <h2 className="font-display font-bold text-base sm:text-xl truncate max-w-[150px] sm:max-w-none">Project Report</h2>
                            </div>
                            <div className="flex items-center gap-1 sm:gap-2">
                                <Button variant="ghost" size="icon" onClick={handleCopy} title="Copy to clipboard" className="h-8 w-8 sm:h-10 sm:w-10">
                                    <Copy className="w-4 h-4" />
                                </Button>
                                <Button variant="ghost" size="icon" onClick={handlePrint} title="Print" className="h-8 w-8 sm:h-10 sm:w-10 hidden sm:flex">
                                    <Printer className="w-4 h-4" />
                                </Button>
                                <Button variant="ghost" size="icon" onClick={handleDownload} title="Download Markdown" className="h-8 w-8 sm:h-10 sm:w-10">
                                    <Download className="w-4 h-4" />
                                </Button>
                                <div className="w-px h-6 bg-border mx-1 sm:mx-2" />
                                <button onClick={onClose} className="p-2 hover:bg-muted rounded-full transition-colors">
                                    <X className="w-5 h-5" />
                                </button>
                            </div>
                        </div>

                        {/* Content */}
                        <div className="flex-1 overflow-y-auto p-5 sm:p-12 print:overflow-visible print:p-0">
                            <div className="max-w-3xl mx-auto prose prose-invert prose-sm sm:prose-base prose-slate print:prose-neutral print:max-w-none">
                                <ReactMarkdown>{summary}</ReactMarkdown>
                            </div>
                        </div>

                        {/* Footer - Hidden on print */}
                        <div className="p-6 border-t border-border bg-card/50 flex justify-end gap-3 shrink-0 print:hidden text-muted-foreground text-[10px] uppercase tracking-widest font-bold items-center">
                            <span>Generated by Idea Navigator AI</span>
                        </div>
                    </motion.div>

                    <style jsx global>{`
            @media print {
              body * {
                visibility: hidden;
              }
              .print\\:block, .print\\:block * {
                visibility: visible;
              }
              .print\\:hidden {
                display: none !important;
              }
              #summary-modal-content, #summary-modal-content * {
                visibility: visible;
              }
              body {
                background: white !important;
                color: black !important;
              }
            }
          `}</style>
                </div>
            )}
        </AnimatePresence>
    );
}
